import Foundation

/// Top-15 food sources for each nutrient (per 100g).
/// Data based on USDA FoodData Central reference values.
/// Daily values used for % calculation.
struct NutrientTopFoods {

    struct FoodSource {
        let name: String
        let per100g: Double
    }

    struct NutrientInfo {
        let dailyValue: Double
        let unit: String
        let foods: [FoodSource]
    }

    static let data: [String: NutrientInfo] = [
        // MARK: - Macros
        "calories": NutrientInfo(dailyValue: 2000.0, unit: "ккал", foods: [
            FoodSource(name: "Масло растительное", per100g: 884.0),
            FoodSource(name: "Сало свиное", per100g: 797.0),
            FoodSource(name: "Масло сливочное", per100g: 717.0),
            FoodSource(name: "Грецкий орех", per100g: 654.0),
            FoodSource(name: "Фундук", per100g: 628.0),
            FoodSource(name: "Миндаль", per100g: 579.0),
            FoodSource(name: "Арахис", per100g: 567.0),
            FoodSource(name: "Семечки подсолнуха", per100g: 584.0),
            FoodSource(name: "Шоколад тёмный", per100g: 546.0),
            FoodSource(name: "Сыр чеддер", per100g: 403.0),
            FoodSource(name: "Свинина жирная", per100g: 376.0),
            FoodSource(name: "Сёмга", per100g: 208.0),
            FoodSource(name: "Авокадо", per100g: 160.0),
            FoodSource(name: "Банан", per100g: 89.0),
            FoodSource(name: "Куриная грудка", per100g: 165.0),
        ]),
        "protein": NutrientInfo(dailyValue: 50.0, unit: "г", foods: [
            FoodSource(name: "Спирулина сушёная", per100g: 57.5),
            FoodSource(name: "Сыр пармезан", per100g: 35.8),
            FoodSource(name: "Тунец", per100g: 29.9),
            FoodSource(name: "Куриная грудка", per100g: 31.0),
            FoodSource(name: "Индейка грудка", per100g: 29.3),
            FoodSource(name: "Говядина постная", per100g: 26.1),
            FoodSource(name: "Чечевица (варёная)", per100g: 9.0),
            FoodSource(name: "Творог", per100g: 18.0),
            FoodSource(name: "Креветки", per100g: 24.0),
            FoodSource(name: "Свинина филе", per100g: 27.3),
            FoodSource(name: "Тофу", per100g: 8.1),
            FoodSource(name: "Лосось", per100g: 20.4),
            FoodSource(name: "Яйцо куриное", per100g: 12.6),
            FoodSource(name: "Арахис", per100g: 25.8),
            FoodSource(name: "Фасоль (варёная)", per100g: 8.7),
        ]),
        "fat": NutrientInfo(dailyValue: 65.0, unit: "г", foods: [
            FoodSource(name: "Масло растительное", per100g: 100.0),
            FoodSource(name: "Сало свиное", per100g: 89.0),
            FoodSource(name: "Масло сливочное", per100g: 81.1),
            FoodSource(name: "Грецкий орех", per100g: 65.2),
            FoodSource(name: "Фундук", per100g: 60.8),
            FoodSource(name: "Миндаль", per100g: 49.9),
            FoodSource(name: "Семечки подсолнуха", per100g: 51.5),
            FoodSource(name: "Арахис", per100g: 49.2),
            FoodSource(name: "Шоколад тёмный", per100g: 31.3),
            FoodSource(name: "Сыр чеддер", per100g: 33.1),
            FoodSource(name: "Авокадо", per100g: 14.7),
            FoodSource(name: "Сёмга", per100g: 13.4),
            FoodSource(name: "Яйцо куриное", per100g: 9.5),
            FoodSource(name: "Свинина жирная", per100g: 29.8),
            FoodSource(name: "Сметана 20%", per100g: 20.0),
        ]),
        "carbs": NutrientInfo(dailyValue: 300.0, unit: "г", foods: [
            FoodSource(name: "Сахар", per100g: 99.8),
            FoodSource(name: "Мёд", per100g: 82.4),
            FoodSource(name: "Рис белый (сухой)", per100g: 79.3),
            FoodSource(name: "Макароны (сухие)", per100g: 75.0),
            FoodSource(name: "Овсянка (сухая)", per100g: 66.3),
            FoodSource(name: "Финики", per100g: 75.0),
            FoodSource(name: "Изюм", per100g: 79.2),
            FoodSource(name: "Хлеб белый", per100g: 49.0),
            FoodSource(name: "Гречка (сухая)", per100g: 71.5),
            FoodSource(name: "Банан", per100g: 22.8),
            FoodSource(name: "Картофель", per100g: 17.5),
            FoodSource(name: "Манго", per100g: 15.0),
            FoodSource(name: "Яблоко", per100g: 13.8),
            FoodSource(name: "Фасоль (варёная)", per100g: 21.1),
            FoodSource(name: "Чечевица (варёная)", per100g: 20.1),
        ]),
        "fiber": NutrientInfo(dailyValue: 25.0, unit: "г", foods: [
            FoodSource(name: "Отруби пшеничные", per100g: 42.8),
            FoodSource(name: "Семена чиа", per100g: 34.4),
            FoodSource(name: "Льняное семя", per100g: 27.3),
            FoodSource(name: "Миндаль", per100g: 12.5),
            FoodSource(name: "Тёмный шоколад", per100g: 10.9),
            FoodSource(name: "Овсянка (сухая)", per100g: 10.6),
            FoodSource(name: "Фасоль (варёная)", per100g: 6.4),
            FoodSource(name: "Чечевица (варёная)", per100g: 7.9),
            FoodSource(name: "Нут (варёный)", per100g: 7.6),
            FoodSource(name: "Авокадо", per100g: 6.7),
            FoodSource(name: "Малина", per100g: 6.5),
            FoodSource(name: "Груша", per100g: 3.1),
            FoodSource(name: "Брокколи", per100g: 2.6),
            FoodSource(name: "Морковь", per100g: 2.8),
            FoodSource(name: "Яблоко", per100g: 2.4),
        ]),

        // MARK: - Fat details
        "saturatedFat": NutrientInfo(dailyValue: 20.0, unit: "г", foods: [
            FoodSource(name: "Кокосовое масло", per100g: 82.5),
            FoodSource(name: "Масло сливочное", per100g: 51.4),
            FoodSource(name: "Сало свиное", per100g: 39.2),
            FoodSource(name: "Пальмовое масло", per100g: 49.3),
            FoodSource(name: "Сыр чеддер", per100g: 21.1),
            FoodSource(name: "Шоколад тёмный", per100g: 18.5),
            FoodSource(name: "Сливки 33%", per100g: 13.9),
            FoodSource(name: "Сметана 20%", per100g: 12.1),
            FoodSource(name: "Свинина жирная", per100g: 11.8),
            FoodSource(name: "Говядина жирная", per100g: 7.3),
            FoodSource(name: "Яйцо куриное", per100g: 3.1),
            FoodSource(name: "Куриная кожа", per100g: 11.4),
            FoodSource(name: "Мороженое", per100g: 6.8),
            FoodSource(name: "Молоко 3.2%", per100g: 2.0),
            FoodSource(name: "Творог 9%", per100g: 5.2),
        ]),
        "monounsaturatedFat": NutrientInfo(dailyValue: 20.0, unit: "г", foods: [
            FoodSource(name: "Оливковое масло", per100g: 73.0),
            FoodSource(name: "Масло авокадо", per100g: 70.6),
            FoodSource(name: "Фундук", per100g: 45.7),
            FoodSource(name: "Миндаль", per100g: 31.6),
            FoodSource(name: "Арахис", per100g: 24.4),
            FoodSource(name: "Авокадо", per100g: 9.8),
            FoodSource(name: "Кешью", per100g: 23.8),
            FoodSource(name: "Свинина филе", per100g: 12.1),
            FoodSource(name: "Говядина", per100g: 8.8),
            FoodSource(name: "Яйцо куриное", per100g: 3.7),
            FoodSource(name: "Сёмга", per100g: 3.8),
            FoodSource(name: "Масло подсолнечное (высокоолеин.)", per100g: 65.7),
            FoodSource(name: "Утка", per100g: 8.2),
            FoodSource(name: "Куриная грудка", per100g: 1.2),
            FoodSource(name: "Сыр гауда", per100g: 7.7),
        ]),
        "polyunsaturatedFat": NutrientInfo(dailyValue: 17.0, unit: "г", foods: [
            FoodSource(name: "Масло льняное", per100g: 67.8),
            FoodSource(name: "Грецкий орех", per100g: 47.2),
            FoodSource(name: "Семечки подсолнуха", per100g: 33.4),
            FoodSource(name: "Масло подсолнечное", per100g: 65.7),
            FoodSource(name: "Семена чиа", per100g: 23.7),
            FoodSource(name: "Льняное семя", per100g: 28.7),
            FoodSource(name: "Сельдь", per100g: 3.4),
            FoodSource(name: "Лосось", per100g: 3.9),
            FoodSource(name: "Скумбрия", per100g: 3.3),
            FoodSource(name: "Тунец", per100g: 1.6),
            FoodSource(name: "Соевое масло", per100g: 57.7),
            FoodSource(name: "Тофу", per100g: 2.9),
            FoodSource(name: "Кунжут", per100g: 21.8),
            FoodSource(name: "Кедровый орех", per100g: 34.1),
            FoodSource(name: "Масло рапсовое", per100g: 28.1),
        ]),
        "cholesterol": NutrientInfo(dailyValue: 300.0, unit: "мг", foods: [
            FoodSource(name: "Мозги говяжьи", per100g: 2500.0),
            FoodSource(name: "Печень куриная", per100g: 563.0),
            FoodSource(name: "Печень говяжья", per100g: 396.0),
            FoodSource(name: "Яйцо куриное (желток)", per100g: 1085.0),
            FoodSource(name: "Яйцо куриное", per100g: 373.0),
            FoodSource(name: "Икра красная", per100g: 588.0),
            FoodSource(name: "Креветки", per100g: 189.0),
            FoodSource(name: "Масло сливочное", per100g: 215.0),
            FoodSource(name: "Сыр чеддер", per100g: 105.0),
            FoodSource(name: "Сало свиное", per100g: 95.0),
            FoodSource(name: "Свинина", per100g: 80.0),
            FoodSource(name: "Говядина", per100g: 73.0),
            FoodSource(name: "Куриная грудка", per100g: 64.0),
            FoodSource(name: "Сметана 20%", per100g: 87.0),
            FoodSource(name: "Молоко 3.2%", per100g: 14.0),
        ]),

        // MARK: - Vitamins
        "vitaminA": NutrientInfo(dailyValue: 900.0, unit: "мкг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 9442.0),
            FoodSource(name: "Печень куриная", per100g: 3296.0),
            FoodSource(name: "Морковь", per100g: 835.0),
            FoodSource(name: "Батат (сладкий картофель)", per100g: 709.0),
            FoodSource(name: "Шпинат", per100g: 469.0),
            FoodSource(name: "Тыква", per100g: 426.0),
            FoodSource(name: "Капуста кейл", per100g: 241.0),
            FoodSource(name: "Масло сливочное", per100g: 684.0),
            FoodSource(name: "Сыр чеддер", per100g: 265.0),
            FoodSource(name: "Яйцо куриное", per100g: 160.0),
            FoodSource(name: "Манго", per100g: 54.0),
            FoodSource(name: "Дыня", per100g: 169.0),
            FoodSource(name: "Перец красный", per100g: 157.0),
            FoodSource(name: "Абрикос", per100g: 96.0),
            FoodSource(name: "Брокколи", per100g: 31.0),
        ]),
        "vitaminB1": NutrientInfo(dailyValue: 1.2, unit: "мг", foods: [
            FoodSource(name: "Дрожжи пищевые", per100g: 11.0),
            FoodSource(name: "Семечки подсолнуха", per100g: 1.48),
            FoodSource(name: "Свинина филе", per100g: 0.87),
            FoodSource(name: "Льняное семя", per100g: 1.64),
            FoodSource(name: "Фисташки", per100g: 0.87),
            FoodSource(name: "Арахис", per100g: 0.64),
            FoodSource(name: "Горох (варёный)", per100g: 0.26),
            FoodSource(name: "Овсянка (сухая)", per100g: 0.76),
            FoodSource(name: "Гречка (сухая)", per100g: 0.43),
            FoodSource(name: "Чечевица (варёная)", per100g: 0.17),
            FoodSource(name: "Печень говяжья", per100g: 0.19),
            FoodSource(name: "Макадамия", per100g: 1.20),
            FoodSource(name: "Хлеб цельнозерновой", per100g: 0.40),
            FoodSource(name: "Кунжут", per100g: 0.79),
            FoodSource(name: "Бразильский орех", per100g: 0.62),
        ]),
        "vitaminB2": NutrientInfo(dailyValue: 1.3, unit: "мг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 2.76),
            FoodSource(name: "Печень куриная", per100g: 1.78),
            FoodSource(name: "Дрожжи пищевые", per100g: 4.0),
            FoodSource(name: "Миндаль", per100g: 1.14),
            FoodSource(name: "Сыр камамбер", per100g: 0.49),
            FoodSource(name: "Яйцо куриное", per100g: 0.46),
            FoodSource(name: "Шпинат", per100g: 0.19),
            FoodSource(name: "Грибы шампиньоны", per100g: 0.40),
            FoodSource(name: "Творог", per100g: 0.18),
            FoodSource(name: "Молоко", per100g: 0.18),
            FoodSource(name: "Лосось", per100g: 0.38),
            FoodSource(name: "Говядина постная", per100g: 0.23),
            FoodSource(name: "Шампиньоны", per100g: 0.40),
            FoodSource(name: "Брокколи", per100g: 0.12),
            FoodSource(name: "Кефир", per100g: 0.17),
        ]),
        "vitaminB3": NutrientInfo(dailyValue: 16.0, unit: "мг", foods: [
            FoodSource(name: "Дрожжи пищевые", per100g: 40.0),
            FoodSource(name: "Тунец", per100g: 18.0),
            FoodSource(name: "Куриная грудка", per100g: 13.7),
            FoodSource(name: "Печень говяжья", per100g: 17.5),
            FoodSource(name: "Индейка грудка", per100g: 11.8),
            FoodSource(name: "Арахис", per100g: 12.1),
            FoodSource(name: "Лосось", per100g: 8.0),
            FoodSource(name: "Говядина постная", per100g: 8.2),
            FoodSource(name: "Свинина филе", per100g: 5.0),
            FoodSource(name: "Грибы шампиньоны", per100g: 3.6),
            FoodSource(name: "Семечки подсолнуха", per100g: 8.3),
            FoodSource(name: "Зелёный горошек", per100g: 2.1),
            FoodSource(name: "Авокадо", per100g: 1.7),
            FoodSource(name: "Картофель", per100g: 1.4),
            FoodSource(name: "Хлеб цельнозерновой", per100g: 4.4),
        ]),
        "vitaminB5": NutrientInfo(dailyValue: 5.0, unit: "мг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 7.17),
            FoodSource(name: "Печень куриная", per100g: 6.23),
            FoodSource(name: "Семечки подсолнуха", per100g: 6.75),
            FoodSource(name: "Грибы шиитаке", per100g: 3.59),
            FoodSource(name: "Авокадо", per100g: 1.39),
            FoodSource(name: "Лосось", per100g: 1.66),
            FoodSource(name: "Куриная грудка", per100g: 1.06),
            FoodSource(name: "Яйцо куриное", per100g: 1.53),
            FoodSource(name: "Чечевица (варёная)", per100g: 0.64),
            FoodSource(name: "Творог", per100g: 0.56),
            FoodSource(name: "Молоко", per100g: 0.36),
            FoodSource(name: "Брокколи", per100g: 0.57),
            FoodSource(name: "Батат", per100g: 0.80),
            FoodSource(name: "Грибы шампиньоны", per100g: 1.50),
            FoodSource(name: "Йогурт", per100g: 0.39),
        ]),
        "vitaminB6": NutrientInfo(dailyValue: 1.7, unit: "мг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 1.08),
            FoodSource(name: "Тунец", per100g: 0.93),
            FoodSource(name: "Лосось", per100g: 0.64),
            FoodSource(name: "Куриная грудка", per100g: 0.60),
            FoodSource(name: "Фисташки", per100g: 1.70),
            FoodSource(name: "Семечки подсолнуха", per100g: 1.35),
            FoodSource(name: "Банан", per100g: 0.37),
            FoodSource(name: "Картофель", per100g: 0.30),
            FoodSource(name: "Говядина постная", per100g: 0.63),
            FoodSource(name: "Чеснок", per100g: 1.24),
            FoodSource(name: "Шпинат", per100g: 0.20),
            FoodSource(name: "Авокадо", per100g: 0.26),
            FoodSource(name: "Грецкий орех", per100g: 0.54),
            FoodSource(name: "Индейка грудка", per100g: 0.81),
            FoodSource(name: "Нут (варёный)", per100g: 0.14),
        ]),
        "vitaminB7": NutrientInfo(dailyValue: 30.0, unit: "мкг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 40.5),
            FoodSource(name: "Яйцо куриное (желток)", per100g: 53.0),
            FoodSource(name: "Арахис", per100g: 34.0),
            FoodSource(name: "Миндаль", per100g: 14.0),
            FoodSource(name: "Грецкий орех", per100g: 9.5),
            FoodSource(name: "Лосось", per100g: 5.0),
            FoodSource(name: "Батат", per100g: 4.6),
            FoodSource(name: "Шпинат", per100g: 6.9),
            FoodSource(name: "Брокколи", per100g: 4.0),
            FoodSource(name: "Сыр чеддер", per100g: 4.2),
            FoodSource(name: "Молоко", per100g: 3.5),
            FoodSource(name: "Овсянка (сухая)", per100g: 7.8),
            FoodSource(name: "Банан", per100g: 2.6),
            FoodSource(name: "Морковь", per100g: 6.1),
            FoodSource(name: "Цветная капуста", per100g: 4.0),
        ]),
        "vitaminB9": NutrientInfo(dailyValue: 400.0, unit: "мкг", foods: [
            FoodSource(name: "Печень куриная", per100g: 588.0),
            FoodSource(name: "Печень говяжья", per100g: 290.0),
            FoodSource(name: "Чечевица (варёная)", per100g: 181.0),
            FoodSource(name: "Шпинат", per100g: 194.0),
            FoodSource(name: "Нут (варёный)", per100g: 172.0),
            FoodSource(name: "Фасоль (варёная)", per100g: 128.0),
            FoodSource(name: "Спаржа", per100g: 149.0),
            FoodSource(name: "Брокколи", per100g: 63.0),
            FoodSource(name: "Авокадо", per100g: 81.0),
            FoodSource(name: "Семечки подсолнуха", per100g: 227.0),
            FoodSource(name: "Арахис", per100g: 240.0),
            FoodSource(name: "Салат латук", per100g: 136.0),
            FoodSource(name: "Свёкла", per100g: 109.0),
            FoodSource(name: "Яйцо куриное", per100g: 47.0),
            FoodSource(name: "Петрушка", per100g: 152.0),
        ]),
        "vitaminB12": NutrientInfo(dailyValue: 2.4, unit: "мкг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 59.3),
            FoodSource(name: "Печень куриная", per100g: 16.6),
            FoodSource(name: "Скумбрия", per100g: 19.0),
            FoodSource(name: "Сардины", per100g: 8.9),
            FoodSource(name: "Лосось", per100g: 3.2),
            FoodSource(name: "Тунец", per100g: 2.9),
            FoodSource(name: "Говядина постная", per100g: 2.6),
            FoodSource(name: "Молоко", per100g: 0.45),
            FoodSource(name: "Яйцо куриное", per100g: 0.89),
            FoodSource(name: "Сыр швейцарский", per100g: 3.06),
            FoodSource(name: "Творог", per100g: 0.46),
            FoodSource(name: "Креветки", per100g: 1.11),
            FoodSource(name: "Йогурт", per100g: 0.37),
            FoodSource(name: "Курица", per100g: 0.31),
            FoodSource(name: "Свинина", per100g: 0.70),
        ]),
        "vitaminC": NutrientInfo(dailyValue: 90.0, unit: "мг", foods: [
            FoodSource(name: "Шиповник", per100g: 426.0),
            FoodSource(name: "Перец болгарский красный", per100g: 128.0),
            FoodSource(name: "Чёрная смородина", per100g: 181.0),
            FoodSource(name: "Киви", per100g: 92.7),
            FoodSource(name: "Брокколи", per100g: 89.2),
            FoodSource(name: "Клубника", per100g: 58.8),
            FoodSource(name: "Апельсин", per100g: 53.2),
            FoodSource(name: "Лимон", per100g: 53.0),
            FoodSource(name: "Капуста кейл", per100g: 120.0),
            FoodSource(name: "Грейпфрут", per100g: 31.2),
            FoodSource(name: "Манго", per100g: 36.4),
            FoodSource(name: "Ананас", per100g: 47.8),
            FoodSource(name: "Помидор", per100g: 13.7),
            FoodSource(name: "Шпинат", per100g: 28.1),
            FoodSource(name: "Петрушка", per100g: 133.0),
        ]),
        "vitaminD": NutrientInfo(dailyValue: 15.0, unit: "мкг", foods: [
            FoodSource(name: "Рыбий жир (масло печени трески)", per100g: 250.0),
            FoodSource(name: "Сёмга / лосось", per100g: 11.0),
            FoodSource(name: "Сельдь", per100g: 16.1),
            FoodSource(name: "Скумбрия", per100g: 16.1),
            FoodSource(name: "Сардины", per100g: 4.8),
            FoodSource(name: "Тунец", per100g: 5.7),
            FoodSource(name: "Яйцо куриное (желток)", per100g: 5.4),
            FoodSource(name: "Грибы шиитаке (на солнце)", per100g: 18.0),
            FoodSource(name: "Печень говяжья", per100g: 1.2),
            FoodSource(name: "Сыр швейцарский", per100g: 1.0),
            FoodSource(name: "Масло сливочное", per100g: 1.5),
            FoodSource(name: "Молоко обогащённое", per100g: 1.3),
            FoodSource(name: "Форель", per100g: 19.0),
            FoodSource(name: "Креветки", per100g: 0.5),
            FoodSource(name: "Угорь", per100g: 23.3),
        ]),
        "vitaminE": NutrientInfo(dailyValue: 15.0, unit: "мг", foods: [
            FoodSource(name: "Масло подсолнечное", per100g: 41.1),
            FoodSource(name: "Семечки подсолнуха", per100g: 35.2),
            FoodSource(name: "Миндаль", per100g: 25.6),
            FoodSource(name: "Фундук", per100g: 15.0),
            FoodSource(name: "Арахис", per100g: 8.3),
            FoodSource(name: "Масло оливковое", per100g: 14.4),
            FoodSource(name: "Шпинат", per100g: 2.0),
            FoodSource(name: "Авокадо", per100g: 2.1),
            FoodSource(name: "Брокколи", per100g: 0.78),
            FoodSource(name: "Киви", per100g: 1.46),
            FoodSource(name: "Манго", per100g: 0.90),
            FoodSource(name: "Перец красный", per100g: 1.58),
            FoodSource(name: "Кедровый орех", per100g: 9.3),
            FoodSource(name: "Лосось", per100g: 1.8),
            FoodSource(name: "Креветки", per100g: 1.2),
        ]),
        "vitaminK": NutrientInfo(dailyValue: 120.0, unit: "мкг", foods: [
            FoodSource(name: "Капуста кейл", per100g: 817.0),
            FoodSource(name: "Шпинат", per100g: 483.0),
            FoodSource(name: "Петрушка", per100g: 1640.0),
            FoodSource(name: "Брокколи", per100g: 101.6),
            FoodSource(name: "Капуста брюссельская", per100g: 177.0),
            FoodSource(name: "Салат латук", per100g: 126.0),
            FoodSource(name: "Спаржа", per100g: 41.6),
            FoodSource(name: "Капуста белокочанная", per100g: 76.0),
            FoodSource(name: "Огурец", per100g: 16.4),
            FoodSource(name: "Масло соевое", per100g: 184.0),
            FoodSource(name: "Масло оливковое", per100g: 60.2),
            FoodSource(name: "Зелёный лук", per100g: 207.0),
            FoodSource(name: "Нут (варёный)", per100g: 4.0),
            FoodSource(name: "Яйцо куриное", per100g: 0.3),
            FoodSource(name: "Авокадо", per100g: 21.0),
        ]),

        // MARK: - Minerals
        "calcium": NutrientInfo(dailyValue: 1000.0, unit: "мг", foods: [
            FoodSource(name: "Сыр пармезан", per100g: 1184.0),
            FoodSource(name: "Кунжут", per100g: 975.0),
            FoodSource(name: "Сыр чеддер", per100g: 721.0),
            FoodSource(name: "Сардины (с костями)", per100g: 382.0),
            FoodSource(name: "Тофу", per100g: 350.0),
            FoodSource(name: "Миндаль", per100g: 269.0),
            FoodSource(name: "Капуста кейл", per100g: 150.0),
            FoodSource(name: "Шпинат", per100g: 99.0),
            FoodSource(name: "Молоко", per100g: 125.0),
            FoodSource(name: "Йогурт", per100g: 110.0),
            FoodSource(name: "Творог", per100g: 83.0),
            FoodSource(name: "Брокколи", per100g: 47.0),
            FoodSource(name: "Фасоль (варёная)", per100g: 35.0),
            FoodSource(name: "Инжир сушёный", per100g: 162.0),
            FoodSource(name: "Апельсин", per100g: 40.0),
        ]),
        "iron": NutrientInfo(dailyValue: 18.0, unit: "мг", foods: [
            FoodSource(name: "Печень свиная", per100g: 17.9),
            FoodSource(name: "Печень куриная", per100g: 8.9),
            FoodSource(name: "Кунжут", per100g: 14.6),
            FoodSource(name: "Печень говяжья", per100g: 6.5),
            FoodSource(name: "Тыквенные семечки", per100g: 8.8),
            FoodSource(name: "Чечевица (варёная)", per100g: 3.3),
            FoodSource(name: "Шпинат", per100g: 2.7),
            FoodSource(name: "Тофу", per100g: 5.4),
            FoodSource(name: "Говядина постная", per100g: 2.6),
            FoodSource(name: "Нут (варёный)", per100g: 2.9),
            FoodSource(name: "Фасоль (варёная)", per100g: 2.2),
            FoodSource(name: "Кешью", per100g: 6.7),
            FoodSource(name: "Шоколад тёмный", per100g: 11.9),
            FoodSource(name: "Киноа (варёная)", per100g: 1.5),
            FoodSource(name: "Овсянка (сухая)", per100g: 4.7),
        ]),
        "magnesium": NutrientInfo(dailyValue: 400.0, unit: "мг", foods: [
            FoodSource(name: "Тыквенные семечки", per100g: 550.0),
            FoodSource(name: "Кунжут", per100g: 351.0),
            FoodSource(name: "Семечки подсолнуха", per100g: 325.0),
            FoodSource(name: "Кешью", per100g: 292.0),
            FoodSource(name: "Миндаль", per100g: 270.0),
            FoodSource(name: "Шоколад тёмный", per100g: 228.0),
            FoodSource(name: "Гречка (сухая)", per100g: 231.0),
            FoodSource(name: "Арахис", per100g: 168.0),
            FoodSource(name: "Шпинат", per100g: 79.0),
            FoodSource(name: "Фасоль (варёная)", per100g: 45.0),
            FoodSource(name: "Авокадо", per100g: 29.0),
            FoodSource(name: "Банан", per100g: 27.0),
            FoodSource(name: "Лосось", per100g: 27.0),
            FoodSource(name: "Овсянка (сухая)", per100g: 177.0),
            FoodSource(name: "Чечевица (варёная)", per100g: 36.0),
        ]),
        "phosphorus": NutrientInfo(dailyValue: 700.0, unit: "мг", foods: [
            FoodSource(name: "Тыквенные семечки", per100g: 1174.0),
            FoodSource(name: "Семечки подсолнуха", per100g: 660.0),
            FoodSource(name: "Сыр пармезан", per100g: 694.0),
            FoodSource(name: "Печень говяжья", per100g: 497.0),
            FoodSource(name: "Лосось", per100g: 252.0),
            FoodSource(name: "Куриная грудка", per100g: 228.0),
            FoodSource(name: "Чечевица (варёная)", per100g: 180.0),
            FoodSource(name: "Йогурт", per100g: 144.0),
            FoodSource(name: "Молоко", per100g: 93.0),
            FoodSource(name: "Яйцо куриное", per100g: 198.0),
            FoodSource(name: "Говядина постная", per100g: 197.0),
            FoodSource(name: "Тофу", per100g: 190.0),
            FoodSource(name: "Арахис", per100g: 376.0),
            FoodSource(name: "Овсянка (сухая)", per100g: 523.0),
            FoodSource(name: "Гречка (сухая)", per100g: 347.0),
        ]),
        "potassium": NutrientInfo(dailyValue: 2600.0, unit: "мг", foods: [
            FoodSource(name: "Курага", per100g: 1162.0),
            FoodSource(name: "Фасоль (варёная)", per100g: 403.0),
            FoodSource(name: "Шпинат", per100g: 558.0),
            FoodSource(name: "Батат", per100g: 337.0),
            FoodSource(name: "Авокадо", per100g: 485.0),
            FoodSource(name: "Лосось", per100g: 363.0),
            FoodSource(name: "Банан", per100g: 358.0),
            FoodSource(name: "Картофель", per100g: 421.0),
            FoodSource(name: "Чечевица (варёная)", per100g: 369.0),
            FoodSource(name: "Тыквенные семечки", per100g: 809.0),
            FoodSource(name: "Молоко", per100g: 150.0),
            FoodSource(name: "Помидор", per100g: 237.0),
            FoodSource(name: "Апельсин", per100g: 181.0),
            FoodSource(name: "Свёкла", per100g: 325.0),
            FoodSource(name: "Йогурт", per100g: 155.0),
        ]),
        "sodium": NutrientInfo(dailyValue: 1500.0, unit: "мг", foods: [
            FoodSource(name: "Соль поваренная", per100g: 38758.0),
            FoodSource(name: "Соевый соус", per100g: 5637.0),
            FoodSource(name: "Сыр пармезан", per100g: 1602.0),
            FoodSource(name: "Оливки консервированные", per100g: 1556.0),
            FoodSource(name: "Колбаса варёная", per100g: 1140.0),
            FoodSource(name: "Хлеб белый", per100g: 491.0),
            FoodSource(name: "Сыр фета", per100g: 1116.0),
            FoodSource(name: "Кетчуп", per100g: 907.0),
            FoodSource(name: "Квашеная капуста", per100g: 661.0),
            FoodSource(name: "Сельдь солёная", per100g: 870.0),
            FoodSource(name: "Сыр чеддер", per100g: 621.0),
            FoodSource(name: "Бекон", per100g: 1717.0),
            FoodSource(name: "Томатный сок", per100g: 269.0),
            FoodSource(name: "Творог", per100g: 364.0),
            FoodSource(name: "Молоко", per100g: 44.0),
        ]),
        "zinc": NutrientInfo(dailyValue: 11.0, unit: "мг", foods: [
            FoodSource(name: "Устрицы", per100g: 78.6),
            FoodSource(name: "Печень говяжья", per100g: 4.0),
            FoodSource(name: "Говядина постная", per100g: 4.8),
            FoodSource(name: "Тыквенные семечки", per100g: 7.8),
            FoodSource(name: "Кунжут", per100g: 7.8),
            FoodSource(name: "Кешью", per100g: 5.8),
            FoodSource(name: "Сыр чеддер", per100g: 3.1),
            FoodSource(name: "Арахис", per100g: 3.3),
            FoodSource(name: "Куриная грудка", per100g: 1.0),
            FoodSource(name: "Чечевица (варёная)", per100g: 1.3),
            FoodSource(name: "Яйцо куриное", per100g: 1.3),
            FoodSource(name: "Шоколад тёмный", per100g: 3.3),
            FoodSource(name: "Овсянка (сухая)", per100g: 3.6),
            FoodSource(name: "Миндаль", per100g: 3.1),
            FoodSource(name: "Креветки", per100g: 1.3),
        ]),
        "copper": NutrientInfo(dailyValue: 0.9, unit: "мг", foods: [
            FoodSource(name: "Печень говяжья", per100g: 9.8),
            FoodSource(name: "Устрицы", per100g: 4.4),
            FoodSource(name: "Кунжут", per100g: 4.1),
            FoodSource(name: "Кешью", per100g: 2.2),
            FoodSource(name: "Шоколад тёмный", per100g: 1.8),
            FoodSource(name: "Семечки подсолнуха", per100g: 1.8),
            FoodSource(name: "Грибы шиитаке", per100g: 0.90),
            FoodSource(name: "Миндаль", per100g: 1.0),
            FoodSource(name: "Грецкий орех", per100g: 1.6),
            FoodSource(name: "Арахис", per100g: 1.1),
            FoodSource(name: "Краб", per100g: 0.67),
            FoodSource(name: "Чечевица (варёная)", per100g: 0.25),
            FoodSource(name: "Авокадо", per100g: 0.19),
            FoodSource(name: "Фундук", per100g: 1.7),
            FoodSource(name: "Тофу", per100g: 0.40),
        ]),
        "manganese": NutrientInfo(dailyValue: 2.3, unit: "мг", foods: [
            FoodSource(name: "Кунжут", per100g: 2.46),
            FoodSource(name: "Овсянка (сухая)", per100g: 4.90),
            FoodSource(name: "Фундук", per100g: 6.18),
            FoodSource(name: "Рис коричневый (сухой)", per100g: 3.74),
            FoodSource(name: "Миндаль", per100g: 2.18),
            FoodSource(name: "Чай чёрный (сухой)", per100g: 26.0),
            FoodSource(name: "Шпинат", per100g: 0.90),
            FoodSource(name: "Ананас", per100g: 0.93),
            FoodSource(name: "Кедровый орех", per100g: 8.80),
            FoodSource(name: "Тыквенные семечки", per100g: 4.54),
            FoodSource(name: "Нут (варёный)", per100g: 0.86),
            FoodSource(name: "Батат", per100g: 0.26),
            FoodSource(name: "Малина", per100g: 0.67),
            FoodSource(name: "Чечевица (варёная)", per100g: 0.49),
            FoodSource(name: "Грецкий орех", per100g: 3.41),
        ]),
        "selenium": NutrientInfo(dailyValue: 55.0, unit: "мкг", foods: [
            FoodSource(name: "Бразильский орех", per100g: 1917.0),
            FoodSource(name: "Тунец", per100g: 90.6),
            FoodSource(name: "Сардины", per100g: 52.7),
            FoodSource(name: "Печень говяжья", per100g: 39.7),
            FoodSource(name: "Куриная грудка", per100g: 27.6),
            FoodSource(name: "Яйцо куриное", per100g: 30.7),
            FoodSource(name: "Семечки подсолнуха", per100g: 53.0),
            FoodSource(name: "Лосось", per100g: 36.5),
            FoodSource(name: "Говядина постная", per100g: 30.0),
            FoodSource(name: "Индейка грудка", per100g: 32.1),
            FoodSource(name: "Креветки", per100g: 38.0),
            FoodSource(name: "Грибы шампиньоны", per100g: 9.3),
            FoodSource(name: "Рис коричневый (варёный)", per100g: 9.8),
            FoodSource(name: "Овсянка (варёная)", per100g: 13.0),
            FoodSource(name: "Творог", per100g: 14.5),
        ]),
        "iodine": NutrientInfo(dailyValue: 150.0, unit: "мкг", foods: [
            FoodSource(name: "Морская капуста (ламинария)", per100g: 2500.0),
            FoodSource(name: "Треска", per100g: 110.0),
            FoodSource(name: "Креветки", per100g: 35.0),
            FoodSource(name: "Тунец", per100g: 17.0),
            FoodSource(name: "Молоко", per100g: 20.0),
            FoodSource(name: "Яйцо куриное", per100g: 24.0),
            FoodSource(name: "Йогурт", per100g: 18.0),
            FoodSource(name: "Сыр чеддер", per100g: 14.0),
            FoodSource(name: "Клюква", per100g: 400.0),
            FoodSource(name: "Картофель", per100g: 6.0),
            FoodSource(name: "Индейка грудка", per100g: 5.0),
            FoodSource(name: "Фасоль (варёная)", per100g: 3.2),
            FoodSource(name: "Хлеб белый", per100g: 4.5),
            FoodSource(name: "Клубника", per100g: 13.0),
            FoodSource(name: "Кукуруза", per100g: 5.0),
        ]),
    ]

    /// Localized display name for a food source. Data stores Russian names as
    /// canonical keys; this resolves them to the current UI language via
    /// `foodNameTranslations` (see NutrientTopFoodsL10n.swift). Falls back to
    /// the Russian name when no translation exists.
    static func localizedName(_ russianName: String) -> String {
        let code = AppLocale.languageCode
        if code == "ru" { return russianName }
        return foodNameTranslations[russianName]?[code] ?? russianName
    }

    /// Localized short unit label ("ккал"/"г"/"мг"/"мкг") via the string catalog.
    static func localizedUnit(_ russianUnit: String) -> String {
        switch russianUnit {
        case "ккал": return String(localized: "ккал")
        case "г": return String(localized: "г")
        case "мг": return String(localized: "мг")
        case "мкг": return String(localized: "мкг")
        default: return russianUnit
        }
    }
}
